import type { ArmorCategory } from "../enums/armorCategory";
import type { ToolCategory } from "../enums/toolCategory";
import type { WeaponCategory } from "../enums/weaponCategory";
import type { ItemDefinitionBase } from "../items/bases/itemDefinitionBase";
import type { FeatGroupLevel, FeatGroupLevelDto } from "../relationships/featGroupLevel";
import type { ItemDefinitionBaseQuantity, ItemDefinitionBaseQuantityDto } from "../relationships/itemDefinitionBaseQuantity";
import type { AbilityScoreDefinition } from "./abilityScoreDefinition";
import type { SkillDefinition } from "./skillDefinition";
import type { SubclassDefinition, SubclassDefinitionDto } from "./subclassDefinition";

export interface CharacterClassDefinition {
    id: string;
    name: string;
    description: string;
    primaryAbilityScoreDefinition: AbilityScoreDefinition | null;
    alternativePrimaryAbilityScoreDefinition: AbilityScoreDefinition | null;
    primaryScoreIsExclusive: boolean;
    hitDie: number;
    savingThrowProficiencies: AbilityScoreDefinition[];
    skillProficiencies: SkillDefinition[];
    numberOfSkillProficiencies: number;
    weaponProficiencies: WeaponCategory[];
    extraWeaponProficiencies: string[];
    toolProficiency: ItemDefinitionBase | null;
    toolProficiencyCategories: ToolCategory[];
    numberOfToolProficiencies: number;
    armorProficiencies: ArmorCategory[];
    startingEquipmentQuantityTables: ItemDefinitionBaseQuantity[];
    startingGp: number;
    featTables: FeatGroupLevel[];
    subclassDefinitions: SubclassDefinition[];
    numberOfPreparedSpells: number[];
    numberOfCantrips: number[];
    levelOneSlots: number[] | null;
    levelTwoSlots: number[] | null;
    levelThreeSlots: number[] | null;
    levelFourSlots: number[] | null;
    levelFiveSlots: number[] | null;
    levelSixSlots: number[] | null;
    levelSevenSlots: number[] | null;
    levelEightSlots: number[] | null;
    levelNineSlots: number[] | null;
    spellcastingAbility: AbilityScoreDefinition | null;
    spellcastingFocus: ItemDefinitionBase | null;
    hasSpellbook: boolean;
    classPoints: number[];
    classDieNumber: number[];
    classDieSides: number[];
    weaponMasteries: number[];
    classBonus: number[];
    defaultStr: number;
    defaultDex: number;
    defaultCon: number;
    defaultInt: number;
    defaultWis: number;
    defaultCha: number;
    fixedHp: number;
}

export interface CharacterClassDefinitionDto {
    id: string;
    name: string;
    description: string;
    primaryAbilityScoreDefinitionId: string | null;
    alternativePrimaryAbilityScoreDefinitionId: string | null;
    primaryScoreIsExclusive: boolean;
    hitDie: number;
    savingThrowProficiencyIds: string[];
    skillProficiencyIds: string[];
    numberOfSkillProficiencies: number;
    weaponProficiencies: WeaponCategory[];
    extraWeaponProficiencies: string[];
    toolProficiencyId: string | null;
    toolProficiencyCategories: ToolCategory[];
    numberOfToolProficiencies: number;
    armorProficiencies: ArmorCategory[];
    startingEquipmentQuantityTables: ItemDefinitionBaseQuantityDto[];
    startingGp: number;
    featTables: FeatGroupLevelDto[];
    subclassDefinitions: SubclassDefinitionDto[];
    numberOfPreparedSpells: number[];
    numberOfCantrips: number[];
    levelOneSlots: number[] | null;
    levelTwoSlots: number[] | null;
    levelThreeSlots: number[] | null;
    levelFourSlots: number[] | null;
    levelFiveSlots: number[] | null;
    levelSixSlots: number[] | null;
    levelSevenSlots: number[] | null;
    levelEightSlots: number[] | null;
    levelNineSlots: number[] | null;
    spellcastingAbilityId: string | null;
    spellcastingFocusId: string | null;
    hasSpellbook: boolean;
    classPoints: number[];
    classDieNumber: number[];
    classDieSides: number[];
    weaponMasteries: number[];
    classBonus: number[];
    defaultStr: number;
    defaultDex: number;
    defaultCon: number;
    defaultInt: number;
    defaultWis: number;
    defaultCha: number;
    fixedHp: number;
}